### ISSUE TITLE
Change default size of home screen bubbles to accommodate longer meet names

### ISSUE THREAD

**Issue by lsherwin10** [spencerdearman/divemeets-app#102]

**Comment by spencerdearman** [comment]
I made the default text size smaller in the branch, let me know what you think
<img width="455" alt="Screenshot 2023-07-05 at 3 50 02 PM" src="https://github.com/spencerdearman/divemeets-app/assets/121642493/0452abeb-9739-4c3b-a499-38628e4b7902">
