### ISSUE TITLE
Alignment/new lines in live results list

### ISSUE THREAD

**Issue by lsherwin10** [spencerdearman/divemeets-app#104]
- Do we want last round place to be two lines on larger text sizes?
- Do we want the name to be left aligned and shifted right when the checkmark appears, or do we want it so that the space for the checkmark is always there and the name is in line with "Diver Order"?

![image](https://github.com/spencerdearman/divemeets-app/assets/41316433/5e904e73-918e-4080-9bf4-ffa7ca4125dd)

**Comment by spencerdearman** [comment]
- I think maybe we somehow abbreviate the Last Round place, maybe with "previous"
- I think maybe the checkmark always appears to the right of the name for continuity, I will make changes and take a picture of them

**Comment by spencerdearman** [comment]
<img width="393" alt="Screenshot 2023-06-27 at 1 38 10 PM" src="https://github.com/spencerdearman/divemeets-app/assets/121642493/b51237df-345e-444d-8117-203f2741e741">

**Comment by lsherwin10** [comment]
Looks great to me, is this pushed?

**Comment by spencerdearman** [comment]
Yes, I will resolve the comment
