### ISSUE TITLE
Date bubbles on home page don't expand with larger font sizes

### ISSUE THREAD

**Issue by lsherwin10** [spencerdearman/divemeets-app#134]
https://github.com/spencerdearman/divemeets-app/assets/41316433/32863a05-c415-4e64-977e-891131600a4e

**Comment by spencerdearman** [comment]
Made a branch for this, is this the thing where I have to add the ....xxxl thing?

**Comment by lsherwin10** [comment]
No I don't think so, this is related to the size of the bubble not changing at all in relation to font sizes. Maybe this could be related to using a frame instead of more dynamic options like padding, but I haven't looked at the code for that

**Comment by spencerdearman** [comment]
<img width="497" alt="Screenshot 2023-07-11 at 11 09 36 AM" src="https://github.com/spencerdearman/divemeets-app/assets/121642493/dafaea4d-6e92-4ca8-aec7-ee25aabb1b94">
This is max text size -- working with surrounding bubble

**Comment by lsherwin10** [comment]
Like it isn't able to expand any farther to grow with text size?
