### ISSUE TITLE
Meet info page colors in events list

### ISSUE THREAD

**Issue by lsherwin10** [spencerdearman/divemeets-app#136]
![image](https://github.com/spencerdearman/divemeets-app/assets/41316433/74e6fcb8-57c1-4e86-8514-32bcbbe79ee8)

**Comment by spencerdearman** [comment]
If you look at the commit for the branch associated with this issue I was able to fix the background and made it look more consistent, but the swipe functionality is no longer working.

**Comment by spencerdearman** [comment]
<img width="481" alt="Screenshot 2023-07-07 at 1 55 10 PM" src="https://github.com/spencerdearman/divemeets-app/assets/121642493/fb26af17-9293-4e56-be8f-ccbb827f3106">

**Comment by spencerdearman** [comment]
https://github.com/spencerdearman/divemeets-app/assets/121642493/96e4ebb9-991f-4430-b382-9ac3d8362dda

You cannot see but I am attempting to do the swipe gesture and this is what happens.

**Comment by lsherwin10** [comment]
Is it going back to the Home page instead of switching pages?
