### ISSUE TITLE
Event title parsing does not capture all cases

### ISSUE THREAD

**Issue by lsherwin10** [spencerdearman/divemeets-app#137]
![image](https://github.com/spencerdearman/divemeets-app/assets/41316433/20a669a5-0166-4b3a-803d-9436703c3891)
![image](https://github.com/spencerdearman/divemeets-app/assets/41316433/6ea0f3de-ba9c-46a6-b74b-70a745000a8c)

**Comment by spencerdearman** [comment]
Sorry i'm confused what you mean/where it isn't parsing?

**Comment by lsherwin10** [comment]
So the events from this meet had part of the name, then parentheses with age group, then the gender, but our parsing didn't get the stuff after and including the parens, so you can't see the age groups or genders in the app. The names just all look the same since it gets cut off before the parens
