### ISSUE TITLE
Coaches with Judging History and Upcoming Meets clash

### ISSUE THREAD

**Issue by lsherwin10** [spencerdearman/divemeets-app#145]
This profile is a coach who also dives Masters, so he has diving history, divers under him as a coach, and judging history all in one profile. Needless to say, things got ugly

https://secure.meetcontrol.com/divemeets/system/profile.php?number=12882
<img width="421" alt="Screenshot 2023-07-08 at 2 59 33 AM" src="https://github.com/spencerdearman/divemeets-app/assets/41316433/a718f608-10cb-421a-8cf1-1bf3875ad4fe">
<img width="398" alt="Screenshot 2023-07-08 at 2 59 53 AM" src="https://github.com/spencerdearman/divemeets-app/assets/41316433/a785e0c2-d4fe-487e-b0ef-7af262181479">

https://github.com/spencerdearman/divemeets-app/assets/41316433/d9cea9aa-5679-477d-bb8f-d98f9b3a1aa4

**Comment by spencerdearman** [comment]
Will complete after parsing updates to profile
