### ISSUE TITLE
Strange clipping of Login bubbles

### ISSUE THREAD

**Issue by lsherwin10** [spencerdearman/divemeets-app#178]
There is some weird clipping effect that is appearing in the top left of the login page near the "Logout" button

![simulator_screenshot_E9C65ED2-6876-4F08-B16A-7694BD10579A](https://github.com/spencerdearman/divemeets-app/assets/41316433/43be4d8e-181c-463d-aac5-f7a100e63dd2)

**Comment by spencerdearman** [comment]
Fixed in searchUI branch
