### ISSUE TITLE
New Menu Bar

### ISSUE THREAD

**Issue by spencerdearman** [spencerdearman/divemeets-app#204]
- Menu Bar may not be best option
- Think of a quicker / more flexible menu bar option

**Comment by lsherwin10** [comment]
I think we could either have the menu bar not collapse and expand and just have it slide between views, or we could have it extend to the bottom of the device and not be "floating". Either way, I think we should consider it hiding itself when the user scrolls down and have it reappear when they scroll back up using a GeometryReader.
