### ISSUE TITLE
Profile view is displayed as long as DiveMeets ID is provided

### ISSUE THREAD

**Issue by lsherwin10** [spencerdearman/divemeets-app#23]
- It's not clear to me if there is an actual login attempt here or what is happening in this case, but if you only enter a DiveMeets ID into the login field and no password and press Submit, it loads the profile page as if the login was successful
- The login could be failing or not, but the profile is being displayed regardless
- The `checkFields()` function should be `&&` instead of `||`, which prevents the issue of submitting a blank password, but submitting invalid passwords also loads the profile view
- It also seems to load a shell of a profile view if you just input things into the boxes, e.g. I input "524" as my ID and "a" as my password, and it genereated a profile with that ID and just no meets, profile picture, or personal info

**Comment by spencerdearman** [comment]
Fixed issues surrounding the login attempts and also with the checkFields() function. I also added an error message that will show up using a DispatchQueue after 2 seconds if the login was not successful.
