### ISSUE TITLE
Clicking on a search result doesn't make the results page full screen

### ISSUE THREAD

**Issue by lsherwin10** [spencerdearman/divemeets-app#25]
How do we want this interaction to be?
- Results appear full screen at the completion of each search by default
- Have it appear half screen by default
- Have it grow to full screen when you click an option by default

Which do we want to do?

**Comment by spencerdearman** [comment]
I think having it open to full screen at the completion of each search is good for the default, however I think we need to remove the ability to have it be half-screen when the user selects an option. This could lead to frustration from the user

**Comment by lsherwin10** [comment]
Agree, may need to look at rewriting this in a different way since I had trouble making this behavior work last time I looked at it

**Comment by spencerdearman** [comment]
I think this would go nicely with the swipe feature as well. I have an idea of a way we could make this into a navigationview and then have it immediately present the view. Maybe we do not allow the user to swipe up and down and instead go straight from the search page to the results and make the user go back to the meetSearch. I would feel comfortable looking at this after finishing the JSON.
