### ISSUE TITLE
Meet year picker jumps back to blank when scrolling during indexing phase

### ISSUE THREAD

**Issue by lsherwin10** [spencerdearman/divemeets-app#39]
- Related to EnvironmentObject updating the published counting values inside caused the entire view to reload on each update
- https://betterprogramming.pub/environment-values-as-an-alternative-to-dependency-injection-in-swiftui-a9de89854afe
- https://www.appsloveworld.com/swift/100/16/swiftui-how-to-prevent-view-to-reload-whole-body

**Comment by spencerdearman** [comment]
Will look into this

**Comment by lsherwin10** [comment]
Promising link:
https://www.mbishop.name/2019/11/odd-behaviors-in-the-swiftui-picker-view/
