### ISSUE TITLE
Some meets show a meet results and meet info link in the database

### ISSUE THREAD

**Issue by lsherwin10** [spencerdearman/divemeets-app#43]
To reproduce:
- Search "National" as the name and "2023" as the year (search is in "update-filter-choices" branch)
- There shuold be two entries for USA Diving National meets each with the same meet ID. One is info, the other is results

- Maybe we already discussed this, or I was supposed to fix it, but what do we want to happen here?

**Comment by spencerdearman** [comment]
I think maybe we can somehow combine the info and the results into a joint page? Or I think we get rid of the info page and then only keep the results page as most likely someone won't be searching for the information from the meet.

**Comment by lsherwin10** [comment]
Right, I think that's why the results page is the only thing that the website links to for past meets.

**Comment by spencerdearman** [comment]
Yeah, I included what it could look like in the flow chart on Figma. What do you think?

**Comment by lsherwin10** [comment]
Now there seems to be 3-4 copies of a given meet when you run the above search

**Comment by spencerdearman** [comment]
I just ran the search and I am only getting 2?

**Comment by lsherwin10** [comment]
The quantity just be related to when we opened the app and where those meets were in the pipeline (upcoming, current, past). I plan to do replacement in the database if they share most of the same data fields, so there should only ever be one meet of a given name on the given dates and at the given location at one time.
